### ISSUE TITLE
Cannot set property '_dragSrcEl' of undefined

### ISSUE THREAD

**Issue by arquadrado** [james2doyle/vue-drag-and-drop#12]
I installed the plugin via npm, did make the Vue instance use it and added the directive v-drag-and-drop to the list element and I got the error in the title. Can anyone help please? I'm using this inside a component, is there any restrictions about using this plugin in nested components? It's also worth noting that I'm using vue 2.0. Thanks in advance

**Comment by james2doyle** [comment]
Hey there. I haven't tested this on Vue 2.0 yet. It's possible that there
are issues there

**Comment by Stettinum** [comment]
any update there ?

**Comment by roman-yerin** [comment]
Zed's dead baby, Zed's dead...
