### ISSUE TITLE
support for vue 2.0?

### ISSUE THREAD

**Issue by beeplin** [james2doyle/vue-drag-and-drop#15]
vue 2.0 has just been release officially. hoping for an upgrade soon~

**Comment by james2doyle** [comment]
Yeah I will be doing that for sure. Just need to find some time to do the
update

**Comment by RizwanAslam** [comment]
My project is on Vue 2 and hardly need such a plugin :( not found a single dnd pugin for vue 2 yet

**Comment by james2doyle** [comment]
Yeah I may try to update it this weekend

**Comment by RizwanAslam** [comment]
This is a great news for me ........ i am very very thankful to you for this 👍

**Comment by Kaijun** [comment]
Hmm, i also checked the doc of Vue 2.0, it seems that `Directive` doesn't support receiving `props` anymore.
We need to implement it in a component way.

**Comment by wlachenal** [comment]
@beeplin @RizwanAslam 

Hello, just in case you were waiting for an update for Vue JS 2 compatability for this plug-in just like me. 

You could check for temporary solution, this was inspired by dnd and mostly this plug-in.
https://github.com/wlachenal/vue-drag-drop

**Comment by brunoksato** [comment]
+1

**Comment by pierophp** [comment]
@wlachenal I made a fix to works with NPM and vue-loader:

https://github.com/pierophp/vue-drag-drop/commit/0144a6a8f7680ad9a02347e34236ef1ac69d458b

If you want I can make a Pull Request in your repo.

Basically the change was:
let DragAndDrop = {};
DragAndDrop.install = function (Vue) {
  ...
}

module.exports = DragAndDrop;

In the main.js:

Vue.use(require('vue-drag-drop'));

**Comment by Stettinum** [comment]
@pierophp  your solution make: Cannot set property '_dragSrcEl' of undefined"
