### ISSUE TITLE
support draggable and droppable when drag or drag is used only

### ISSUE THREAD

**Issue by Jerret321** [james2doyle/vue-drag-and-drop#16]
```javascript
<li class="item" id="{{$index}}" v-for="item in list"
        v-drag-and-drop
        drag-start="handleDragStart"
        drag-over="handleDragOver"
        drag-enter="handleDragEnter"
        drag-leave="handleDragLeave"
        drag-end="handleDragEnd"
        drop="handleDrop"
        drag="handleDrag",
        draggable="true",
        droppable="false"
    >
      <span>{{item.name}}</span>
    </li>
```

when `draggbale` is false, the element can not be dragged;
when `droppable` is false, the element can not be dropped,
the option `draggble` and `droppable` is both default true

**Comment by mn113** [comment]
Will this make it so I can set a single element as the droppable? I'm having an issue where too many  child elements are considered droppables.

**Comment by Jerret321** [comment]
Yes, a single element can be used as the draggable or droppable.

**Comment by Jerret321** [comment]
someone ask this question on [#14](https://github.com/james2doyle/vue-drag-and-drop/issues/14). I also need the functions support, so I pull the request. If there is no problem, please merge the request. Thank you.
