### ISSUE TITLE
Support for touch devices

### ISSUE THREAD

**Issue by blogui91** [james2doyle/vue-drag-and-drop#2]
Hi, you saved my life, i think this is the only one Directive to create Drag and drop for Vue 1.0.* However i just noticed, it does not work for touch devices, it may be a good approach for future.

**Comment by james2doyle** [comment]
Yeah it would be nice. This library simply wraps the native drag and drop in html5, so unfortunately that will never happen. There is no support, and probably never will be any, for native "drag and drop" on mobile. See this [chart](http://caniuse.com/#feat=dragndrop).

The reason for this is that touch devices already have the necessary events (touch events) to implement drag and drop without need the additional apis that the desktop drag and drop has.

If you need a cross-platform solution, you should check out [this awesome library called pep!](http://pep.briangonzalez.org/).

**Comment by blogui91** [comment]
Thanks a lot! i will take a look, greetings!
