### ISSUE TITLE
cause an error when remove the drop item

### ISSUE THREAD

**Issue by LoeiFy** [james2doyle/vue-drag-and-drop#20]
this plugin help me a lot, thanks!

i want to change the drop item position but not swap their position

what i do is remove the drop item from the list and then insert the item into the list

``` js
        handleDrop(a, b) {
            a = a.getAttribute('data-index');
            b = b.getAttribute('data-index');

            const temp = JSON.parse(JSON.stringify(this.dialogs[a]));

            this.dialogs.splice(a, 1)
            this.dialogs.splice(b, 0, temp)
        }
```

but this cause an error

`Uncaught TypeError: Cannot read property 'undefined' of null`

error here

``` js
        this.handleDragEnd = function(e) {
          e.target.classList.remove('dragging', 'drag-over', 'drag-enter');

          // error 
          if (typeof(this.vm[this.params.dragEnd]) === 'function') {

            this.vm[this.params.dragEnd].call(this, e.target, e);
          }
        }.bind(this);
```

i think the error caused by the item be removed. and the solution is detect if the item exist when ready to call the `dropEnd` method

@james2doyle what do you think ?   any other solution ?

**Comment by james2doyle** [comment]
Updated for Vue 2. Please try again
