### ISSUE TITLE
Dropping an element triggers the browser to open that element

### ISSUE THREAD

**Issue by falloutghost** [james2doyle/vue-drag-and-drop#6]
I try to use the directive like this:

```
<ul class="ImageFileUpload__images-list row">
            <li v-for="image in persistedImages" class="ImageFileUpload__image-wrapper col-md-3 col-xs-12" v-drag-and-drop drag-over="handleDragOver" drop="handleDrop">
                <div>drag me</div>
                <button type="button" class="btn btn-red ImageFileUpload__remove-image-button"
                        @click="removeImage(image)">
                    <span class="icon icon-delete"></span>
                </button>
                <img :src="image.webpath" class="ImageFileUpload__image img-responsive">
            </li>
        </ul>
```

It basically works, I see both of the triggered event outputs (drag-over and drop) in the console. However, once I drop the element where I want it to go, the browser opens that file in the current tab, taking me away from the site.

This also happens for elements that don't contain or are images - the browser then just tries to load the URL "http://www.*.com".

Is there some way to turn this behavior off or to get access to the underlying event object (in order to call `event.preventDefault()`)?

Tested with Firefox 45.0.2.

**Comment by james2doyle** [comment]
Hmm that is some weird behaviour. We are actually using code specifically to [block redirects](https://github.com/james2doyle/vue-drag-and-drop/blob/master/vue.drag-and-drop.js#L61-L63)

Does this happen on other browsers?

**Comment by falloutghost** [comment]
Works fine in Chrome Version 50.0.2661.86 (64-bit).
I'm on Ubuntu 15.10.

**Comment by falloutghost** [comment]
I implemented my own solution in the meanwhile, and just noticed that I experience the same behavior as described above if I add `event.stopPropagation()` to my `onDrop` function. Without that, everything works fine (I didn't test this extensively though, it's for a backend application and I can assume that all clients are running Firefox).

I.e., you could consider removing lines `61--64` in `vue.drag-and-drop.js`.

**Comment by maple-leaf** [comment]
confirm this issue on firefox.

**Comment by Comp0ser** [comment]
+1 on firefox @ archlinux

https://github.com/james2doyle/vue-drag-and-drop/pull/9

**Comment by StefanNeuser** [comment]
+1 on firefox

**Comment by james2doyle** [comment]
New version released. Should stop this issue: https://github.com/james2doyle/vue-drag-and-drop/releases/tag/2.1.0
