### ISSUE TITLE
Preventing drag on input and textarea

### ISSUE THREAD

**Issue by iJackUA** [james2doyle/vue-drag-and-drop#7]
Is it possible to prevent drag on input or textarea if they are placed inside draggable div? (to allow text selection with mouse, but outer div should be still draggable)

I have tried to override `dragstart`, `dragenter` etc. events on input and stop/prevent event propagation, but no luck.

**Comment by james2doyle** [comment]
I have no experience with this. But you may have to add additional code to preventDefault on child elements of the draggable parent
